packages:
  - apps/*
  - packages/*
  - services/*
  - tools/*
allowBuilds:
  '@google/genai': false
  core-js: false
  esbuild: true
  lefthook: true
  protobufjs: false
overrides:
  use-sync-external-store: 1.6.0
minimumReleaseAgeExclude:
  - "@pieai/doc-gov"
  - "@pieai/pro-gov"
  - '@pieai/swimmer-ui-kit@0.9.0 || 1.0.0 || 1.0.1'
