import { VOICE_SYNTHESIS_SPEC, type VoiceCastContract } from "./synthesisContract";

export interface GovernedVoiceLine {
  readonly key: string;
  readonly characterId: string;
  readonly text: string;
  readonly chapterId: string;
  readonly sceneId: string | null;
  readonly language: "zh-CN" | "en";
}

export interface GovernedVoiceFileRecord {
  readonly key: string;
  readonly sha256: string | null;
  readonly bytes: number | null;
  readonly valid: boolean;
}

export function buildVoiceLedgerText(input: {
  readonly currentText: string;
  readonly generated: ReadonlyMap<string, GovernedVoiceFileRecord>;
  readonly lines: ReadonlyMap<string, GovernedVoiceLine>;
  readonly orphanKeys: readonly string[];
}): string {
  const replacedKeys = new Set([...input.generated.keys(), ...input.orphanKeys]);
  const retainedLines = input.currentText
    .trimEnd()
    .split(/\r?\n/u)
    .filter((line, index) => {
      if (index === 0 || !line.startsWith("voice-")) return true;
      const assetId = line.split(",", 1)[0] ?? "";
      return !replacedKeys.has(assetId.slice("voice-".length));
    });
  const generatedRows = [...input.generated.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, record]) => {
      const line = input.lines.get(key);
      if (!line || !record.sha256 || !record.bytes || !record.valid) {
        throw new Error(`cannot build governed ledger row for invalid generated clip ${key}`);
      }
      const notes =
        `${line.chapterId}_static_voice_${line.language.replace("-", "_")}_${line.characterId}`.replace(
          /[^a-zA-Z0-9_]/gu,
          "_",
        );
      return [
        `voice-${key}`,
        `apps/web/public/assets/voice/${key}.mp3`,
        record.sha256,
        String(record.bytes),
        "ai_generated_minimax_speech02_turbo",
        "demo_approved_commercial_evidence_pending",
        notes,
      ].join(",");
    });
  return [...retainedLines, ...generatedRows].join("\n") + "\n";
}

export function buildVoiceProvenance(input: {
  readonly line: GovernedVoiceLine;
  readonly cast: VoiceCastContract;
  readonly operator: string;
  readonly generatedAt: string;
  readonly sourceUrl: string;
}): string {
  const audio = VOICE_SYNTHESIS_SPEC.audio;
  return `---
assetId: voice-${input.line.key}
kind: audio_voice
tool: minimax-api
model: ${VOICE_SYNTHESIS_SPEC.model}
generatedAt: ${input.generatedAt}
sourceUrl: ${input.sourceUrl}
operator: ${input.operator}
outputSpec: mp3 ${Math.round(audio.bitrate / 1000)}kbps ${Math.round(audio.sampleRate / 1000)}kHz mono
---

# Prompt (verbatim)

${input.line.text}

# Notes

- Runtime key: \`${input.line.key}\`
- Chapter / scene: \`${input.line.chapterId}\` / \`${input.line.sceneId ?? "unknown"}\`
- Cast: \`${input.line.characterId}\` → \`${input.cast.voiceId}\`
- Request settings: ${input.cast.languageBoost} language boost; speed ${input.cast.speed}; volume ${VOICE_SYNTHESIS_SPEC.volume}; pitch ${input.cast.pitch}; ${audio.sampleRate / 1000} kHz; ${audio.bitrate / 1000} kbps; mono MP3.
- Generated by the reviewed global voice sync; catalog activation, ledger, provenance and legacy-debt baseline commit as one rollback transaction.
`;
}
