// This file is generated by scripts/generate-story-catalog-types.mjs.
// Do not edit it by hand; edit catalog/story-catalog.json and regenerate instead.

export const PRODUCTION_STORY_CATALOG_IDS = ["draft-ch01", "draft-ch02", "draft-ch03"] as const;

export type ProductionStoryCatalogId = (typeof PRODUCTION_STORY_CATALOG_IDS)[number];

export const DEV_STORY_CATALOG_IDS = ["prototype-act1", "chapter-01-trial"] as const;

export type DevStoryCatalogId = (typeof DEV_STORY_CATALOG_IDS)[number];

export const STORY_CATALOG_IDS = [
  "draft-ch01",
  "draft-ch02",
  "draft-ch03",
  "prototype-act1",
  "chapter-01-trial",
] as const;

export type StoryCatalogId = (typeof STORY_CATALOG_IDS)[number];

export const STORY_PACKAGE_IDS = ["draft-2026-07"] as const;

export type StoryPackageId = (typeof STORY_PACKAGE_IDS)[number];

export const DEFAULT_STORY_PACKAGE_ID = "draft-2026-07" as const satisfies StoryPackageId;

export const DEFAULT_STORY_ID = "draft-ch01" as const satisfies StoryCatalogId;
