import type { PrototypeSceneCard } from "@supaluv/shared";
/** Auto-aligned with densified ch01.ink — novel-to-script expansion. */
export const ch01Scenes = [
  {
    id: "ch01_office_stare",
    title: "办公室 · 三分十七秒",
    purpose: "Densified novel beat.",
    visualPlaceholder: "办公室 · 三分十七秒",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    stageMotion: "slow_push",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "notify-soft",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_office_bug_eyes" }],
  },
  {
    id: "ch01_office_bug_eyes",
    title: "办公室 · 反光",
    purpose: "Densified novel beat.",
    visualPlaceholder: "办公室 · 反光",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_office_shame" }],
  },
  {
    id: "ch01_office_shame",
    title: "办公室 · warmth sample",
    purpose: "Densified novel beat.",
    visualPlaceholder: "办公室 · warmth sample",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_office_delete_or_shot" }],
  },
  {
    id: "ch01_office_delete_or_shot",
    title: "办公室 · 删除或截图",
    purpose: "Densified novel beat + constrained AI side choice demo.",
    visualPlaceholder: "办公室 · 删除或截图",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    aiBranch: {
      enabled: true,
      waitLabel: "灵感生成中…",
      rejoinSceneId: "ch01_phone_buzz",
      maxAiBeats: 2,
      context:
        "苏明在办公室面对「不会嫌弃你」脏样本。作者已写删除/截图两支。请给一个黑色喜剧第三条：更怂、更程序员、不色情。短选项文案+1-2句对白后必须回到物业短信线。",
      artPool: ["bg-office-night", "bg-lobby-white", "bg-rental-room"],
      portraitPool: [
        "suming-panic",
        "suming-shame",
        "suming-restless",
        "suming-lonely",
        "suming-tempted",
        "suming-uncanny",
        "suming-committed",
      ],
      speakerPool: ["苏明", "旁白"],
    },
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [
      { label: "立刻删掉，假装什么都没发生", to: "ch01_after_delete" },
      { label: "先截图备份，文件夹叫 not_for_review", to: "ch01_screenshot_save" },
    ],
  },
  {
    id: "ch01_after_delete",
    title: "办公室 · 删除之后",
    purpose: "Densified novel beat.",
    visualPlaceholder: "办公室 · 删除之后",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_phone_buzz" }],
  },
  {
    id: "ch01_screenshot_save",
    title: "办公室 · not_for_review",
    purpose: "Densified novel beat.",
    visualPlaceholder: "办公室 · not_for_review",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_coworker_peek" }],
  },
  {
    id: "ch01_coworker_peek",
    title: "办公室 · 同事探头",
    purpose: "Densified novel beat.",
    visualPlaceholder: "办公室 · 同事探头",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-panic",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "panic",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [
      { label: "用身体挡住屏幕，胡扯「很正经的文案」", to: "ch01_coworker_bluff" },
      { label: "差点儿说实话，最后还是胡扯", to: "ch01_coworker_bluff" },
    ],
  },
  {
    id: "ch01_coworker_bluff",
    title: "办公室 · 胡扯过关",
    purpose: "Densified novel beat.",
    visualPlaceholder: "办公室 · 胡扯过关",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_phone_buzz" }],
  },
  {
    id: "ch01_phone_buzz",
    title: "手机 · 东西我放这了",
    purpose: "Densified novel beat.",
    visualPlaceholder: "手机 · 东西我放这了",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-restless",
    bgmKey: "night-ambient",
    sfxKey: "notify-soft",
    speaker: "林晓棠",
    mood: "restless",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [
      { label: "去物业", to: "ch01_elevator" },
      { label: "先假装没看见，再去", to: "ch01_delay_four_min" },
    ],
  },
  {
    id: "ch01_delay_four_min",
    title: "办公室 · 多坐四分钟",
    purpose: "Densified novel beat.",
    visualPlaceholder: "办公室 · 多坐四分钟",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "去物业", to: "ch01_elevator" }],
  },
  {
    id: "ch01_elevator",
    title: "电梯 · 逃兵",
    purpose: "Densified novel beat.",
    visualPlaceholder: "电梯 · 逃兵",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "sterile",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_property_bag" }],
  },
  {
    id: "ch01_property_bag",
    title: "物业 · 白袋子",
    purpose: "Densified novel beat.",
    visualPlaceholder: "物业 · 白袋子",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "sterile",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_bag_contents" }],
  },
  {
    id: "ch01_bag_contents",
    title: "物业 · 袋中物",
    purpose: "Densified novel beat.",
    visualPlaceholder: "物业 · 袋中物",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "sterile",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "回家", to: "ch01_hallway_zhoulu" }],
  },
  {
    id: "ch01_hallway_zhoulu",
    title: "楼道 · 周鹿",
    purpose: "Densified novel beat.",
    visualPlaceholder: "楼道 · 周鹿",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-lonely",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "周鹿",
    mood: "lonely",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_hallway_appliance" }],
  },
  {
    id: "ch01_hallway_appliance",
    title: "楼道 · 大型家电",
    purpose: "Densified novel beat.",
    visualPlaceholder: "楼道 · 大型家电",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-lonely",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "周鹿",
    mood: "lonely",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "回自己房间", to: "ch01_rental_enter" }],
  },
  {
    id: "ch01_rental_enter",
    title: "出租屋 · 进门",
    purpose: "Densified novel beat.",
    visualPlaceholder: "出租屋 · 进门",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-lonely",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "lonely",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_rental_room" }],
  },
  {
    id: "ch01_rental_room",
    title: "出租屋 · 裂缝",
    purpose: "Densified novel beat.",
    visualPlaceholder: "出租屋 · 裂缝",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-lonely",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "lonely",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [
      { label: "躺着，让脑子安静一点", to: "ch01_memory_shame" },
      { label: "直接掏手机找点什么", to: "ch01_forum_title" },
    ],
  },
  {
    id: "ch01_memory_shame",
    title: "记忆 · 恶心",
    purpose: "Densified novel beat.",
    visualPlaceholder: "记忆 · 恶心",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "notify-soft",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_memory_p0" }],
  },
  {
    id: "ch01_memory_p0",
    title: "记忆 · 正常 / P0",
    purpose: "Densified novel beat.",
    visualPlaceholder: "记忆 · 正常 / P0",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "notify-soft",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "……继续", to: "ch01_zhoulu_knock" }],
  },
  {
    id: "ch01_zhoulu_knock",
    title: "墙外 · 猫都焦虑了",
    purpose: "Densified novel beat.",
    visualPlaceholder: "墙外 · 猫都焦虑了",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-lonely",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "周鹿",
    mood: "lonely",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_zhoulu_anime_cry" }],
  },
  {
    id: "ch01_zhoulu_anime_cry",
    title: "墙外 · 番剧在哭",
    purpose: "Densified novel beat.",
    visualPlaceholder: "墙外 · 番剧在哭",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-lonely",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "周鹿",
    mood: "lonely",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "打开匿名论坛", to: "ch01_forum_title" }],
  },
  {
    id: "ch01_forum_title",
    title: "论坛 · 标题钩子",
    purpose: "Densified novel beat.",
    visualPlaceholder: "论坛 · 标题钩子",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-restless",
    bgmKey: "lonely-pad",
    sfxKey: "notify-soft",
    speaker: "旁白",
    mood: "restless",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_forum_comments" }],
  },
  {
    id: "ch01_forum_comments",
    title: "论坛 · 评论区",
    purpose: "Densified novel beat.",
    visualPlaceholder: "论坛 · 评论区",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-restless",
    bgmKey: "lonely-pad",
    sfxKey: "notify-soft",
    speaker: "旁白",
    mood: "restless",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_forum_night" }],
  },
  {
    id: "ch01_forum_night",
    title: "论坛 · 牙酸的笑",
    purpose: "Densified novel beat.",
    visualPlaceholder: "论坛 · 牙酸的笑",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-restless",
    bgmKey: "lonely-pad",
    sfxKey: "notify-soft",
    speaker: "旁白",
    mood: "restless",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [
      { label: "点进产品页", to: "ch01_product_clean" },
      { label: "再刷三分钟假装只是路过", to: "ch01_forum_linger" },
    ],
  },
  {
    id: "ch01_forum_linger",
    title: "论坛 · 假装路过",
    purpose: "Densified novel beat.",
    visualPlaceholder: "论坛 · 假装路过",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-restless",
    bgmKey: "lonely-pad",
    sfxKey: "notify-soft",
    speaker: "苏明",
    mood: "restless",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_forum_search" }],
  },
  {
    id: "ch01_forum_search",
    title: "论坛 · 搜索框",
    purpose: "Densified novel beat + constrained AI side choice.",
    visualPlaceholder: "论坛 · 搜索框",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-restless",
    bgmKey: "lonely-pad",
    sfxKey: "notify-soft",
    speaker: "苏明",
    mood: "restless",
    aiBranch: {
      enabled: true,
      waitLabel: "灵感生成中…",
      rejoinSceneId: "ch01_product_clean",
      maxAiBeats: 2,
      context:
        "苏明在匿名论坛搜索相关关键词。作者选项是点进产品页。请给更怂/更自嘲的第三条：短选项+1-2句后必须回到产品页。黑色喜剧，禁止色情。",
      artPool: ["bg-rental-room", "bg-office-night", "bg-product-page"],
      portraitPool: [
        "suming-restless",
        "suming-shame",
        "suming-panic",
        "suming-lonely",
        "suming-tempted",
        "suming-uncanny",
      ],
      speakerPool: ["苏明", "旁白"],
    },
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "点进产品页", to: "ch01_product_clean" }],
  },
  {
    id: "ch01_product_clean",
    title: "产品页 · 医院走廊",
    purpose: "Densified novel beat.",
    visualPlaceholder: "产品页 · 医院走廊",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    stageMotion: "flash",
    portraitKey: "suming-tempted",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "tempted",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_product_page" }],
  },
  {
    id: "ch01_product_page",
    title: "产品页 · 不会嫌弃你",
    purpose: "Densified novel beat.",
    visualPlaceholder: "产品页 · 不会嫌弃你",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-tempted",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "tempted",
    characterSlotLock: { slotIds: ["robot_aila", "robot_kai"] },
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [
      { label: "打开演示对话", to: "ch01_demo_loading" },
      { label: "直接滑向支付", to: "ch01_demo_loading" },
      { label: "先看三遍隐私政策，假装技术调研", to: "ch01_privacy_pretend" },
      { label: "返回出租屋再想想", to: "ch01_rental_room", kind: "return" },
    ],
  },
  {
    id: "ch01_privacy_pretend",
    title: "产品页 · 隐私政策",
    purpose: "Densified novel beat.",
    visualPlaceholder: "产品页 · 隐私政策",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-tempted",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "tempted",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "打开演示对话", to: "ch01_demo_loading" }],
  },
  {
    id: "ch01_demo_loading",
    title: "演示 · 加载两秒",
    purpose: "Densified novel beat.",
    visualPlaceholder: "演示 · 加载两秒",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-uncanny",
    bgmKey: "soft-piano",
    sfxKey: "notify-soft",
    speaker: "演示对话",
    mood: "uncanny",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_demo_echo" }],
  },
  {
    id: "ch01_demo_echo",
    title: "演示 · 回声",
    purpose: "Densified novel beat.",
    visualPlaceholder: "演示 · 回声",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-uncanny",
    bgmKey: "soft-piano",
    sfxKey: "notify-soft",
    speaker: "演示对话",
    mood: "uncanny",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_demo_react" }],
  },
  {
    id: "ch01_demo_react",
    title: "演示 · 操",
    purpose: "Densified novel beat.",
    visualPlaceholder: "演示 · 操",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-uncanny",
    bgmKey: "soft-piano",
    sfxKey: "notify-soft",
    speaker: "演示对话",
    mood: "uncanny",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [
      { label: "继续下单流程", to: "ch01_address_form" },
      { label: "关掉演示，心里更乱了", to: "ch01_address_form" },
    ],
  },
  {
    id: "ch01_address_form",
    title: "订单 · 先填地址",
    purpose: "Densified novel beat.",
    visualPlaceholder: "订单 · 先填地址",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-tempted",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "tempted",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_emergency_contact" }],
  },
  {
    id: "ch01_emergency_contact",
    title: "订单 · 紧急联系人",
    purpose: "Densified novel beat.",
    visualPlaceholder: "订单 · 紧急联系人",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-tempted",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "tempted",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_courier_fantasy" }],
  },
  {
    id: "ch01_courier_fantasy",
    title: "订单 · 心跳",
    purpose: "Densified novel beat + constrained AI side choice.",
    visualPlaceholder: "订单 · 心跳",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-tempted",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "tempted",
    aiBranch: {
      enabled: true,
      waitLabel: "灵感生成中…",
      rejoinSceneId: "ch01_payment",
      maxAiBeats: 2,
      context:
        "苏明填地址后心跳加速。作者选项：确认支付 / 再看价格。请给第三条更程序员黑色幽默的犹豫（短选项+1-2句），然后必须进入支付节点。禁止色情。",
      artPool: ["bg-product-page", "bg-rental-room", "bg-lobby-white"],
      portraitPool: [
        "suming-tempted",
        "suming-uncanny",
        "suming-committed",
        "suming-shame",
        "suming-panic",
        "suming-restless",
        "suming-lonely",
      ],
      speakerPool: ["旁白", "苏明"],
    },
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [
      { label: "确认地址，进入支付", to: "ch01_payment" },
      { label: "再看一眼价格", to: "ch01_price_look" },
    ],
  },
  {
    id: "ch01_price_look",
    title: "订单 · 再看价格",
    purpose: "Densified novel beat.",
    visualPlaceholder: "订单 · 再看价格",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-tempted",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "tempted",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "支付", to: "ch01_payment" }],
  },
  {
    id: "ch01_payment",
    title: "支付 · 对猫口型",
    purpose: "Densified novel beat.",
    visualPlaceholder: "支付 · 对猫口型",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-committed",
    bgmKey: "soft-piano",
    sfxKey: "payment-chime",
    speaker: "旁白",
    mood: "committed",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_order_done" }],
  },
  {
    id: "ch01_order_done",
    title: "支付 · 实验不是判决",
    purpose: "Densified novel beat.",
    visualPlaceholder: "支付 · 实验不是判决",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-committed",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "committed",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "继续", to: "ch01_what_he_bought" }],
  },
  {
    id: "ch01_what_he_bought",
    title: "支付 · 付费会员的孤独",
    purpose: "Densified novel beat.",
    visualPlaceholder: "支付 · 付费会员的孤独",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-lonely",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "chapter-01-narrative-draft",
    choices: [{ label: "躺着听世界运转", to: "ch01_chapter_end" }],
  },
  {
    id: "ch01_chapter_end",
    title: "章末 · 空气很正常",
    purpose: "Densified novel beat.",
    visualPlaceholder: "章末 · 空气很正常",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-lonely",
    bgmKey: "soft-piano",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    aiEnding: {
      id: "ch01-ai-ending-v1",
      storyId: "ch01",
      entryId: "ch01_chapter_end",
      allowedOutcomeAnchors: [
        "keep_order_and_call_zhoulu",
        "cancel_order_and_admit_loneliness",
        "double_down_on_robot_future",
      ],
      requiredFacts: [
        "苏明已经完成机器人订单",
        "周鹿住在同一栋楼并看穿过他的窘迫",
        "本章的核心是羞耻、孤独与把亲密关系产品化",
      ],
      unresolvedThreads: ["苏明会不会承认自己真正想要的不是机器", "订单到货前他是否联系周鹿"],
      characterInvariants: [
        "苏明嘴硬、怂、程序员式自我辩护，但不能突然变成情圣",
        "周鹿尖锐、清醒，不负责治愈苏明",
      ],
      toneConstraints: ["成人黑色喜剧与性喜剧能量", "辛辣但不露骨", "选择必须造成可见后果"],
      forbiddenOutcomes: [
        "露骨色情",
        "未成年人",
        "无铺垫死亡",
        "一切都是梦",
        "突然宣讲相信爱情",
        "角色遗忘本章事实",
      ],
      allowedSlotIds: ["lead_suming", "lead_zhou_lu", "robot_aila", "robot_kai"],
      allowedBackgrounds: [
        "bg-product-page",
        "bg-rental-room",
        "bg-lobby-white",
        "bg-office-night",
      ],
      maxSegments: 8,
      targetChoicePoints: { min: 3, max: 5 },
      choicesPerPoint: { min: 2, max: 4 },
      maxTotalCharacters: 12000,
      maxOptionalStills: 2,
      forceTerminalAtSegment: 8,
    },
    noncanonical: true,
    source: "chapter-01-narrative-draft",
  },
] as const satisfies readonly PrototypeSceneCard[];
