import type { PrototypeSceneCard } from "@supaluv/shared";

export const chapter01TrialScenes: readonly PrototypeSceneCard[] = [
  {
    id: "act1_trial_property_photo",
    title: "Property Photo",
    purpose: "Open the trial pipeline with the breakup logistics photo and message.",
    speaker: "旁白",
    mood: "stung",
    backgroundKey: "lobby-white",
    visualPlaceholder: "White bag, lobby tile, cold phone glow.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_office_shame_test",
  },
  {
    id: "act1_trial_office_shame_test",
    title: "Office Shame Test",
    purpose: "Show Su Ming at work testing the shame-response prompt.",
    speaker: "苏明",
    mood: "shame",
    backgroundKey: "office-night",
    visualPlaceholder: "Monitor glow, cursor, warm coffee gone cold.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_coworker_pressure",
  },
  {
    id: "act1_trial_coworker_pressure",
    title: "Coworker Pressure",
    purpose: "Introduce outside judgment and workplace noise around the test prompt.",
    speaker: "周骁",
    mood: "exposed",
    backgroundKey: "office-night",
    visualPlaceholder: "Office chair wheels, lemon tea cup, side glance.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_self_authored_reply",
  },
  {
    id: "act1_trial_self_authored_reply",
    title: "Self Authored Reply",
    purpose: "Mark the moment Su Ming types the one line that lands emotionally.",
    speaker: "苏明",
    mood: "careful",
    backgroundKey: "office-night",
    visualPlaceholder: "Black UI, white type, green pass indicator.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_meeting_sell_safety",
  },
  {
    id: "act1_trial_meeting_sell_safety",
    title: "Meeting Sell Safety",
    purpose: "Compress the meeting into a beat about monetizing being 'received.'",
    speaker: "旁白",
    mood: "numb",
    backgroundKey: "office-night",
    visualPlaceholder: "Meeting table, data cable, sterile conference light.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_lunch_heat_memory",
  },
  {
    id: "act1_trial_lunch_heat_memory",
    title: "Lunch Heat Memory",
    purpose: "Shift from work pressure into bodily discomfort and old associative shame.",
    speaker: "旁白",
    mood: "dizzy",
    backgroundKey: "food-court",
    visualPlaceholder: "Mall heat, crossing light, rubber smell, memory flash.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_forum_hint",
  },
  {
    id: "act1_trial_forum_hint",
    title: "Forum Hint",
    purpose: "Introduce the companion-device forum as the first visible path into the pipeline.",
    speaker: "周骁",
    mood: "tempted",
    backgroundKey: "food-court",
    visualPlaceholder: "Food court tray, phone screen, gray forum post.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    choices: [
      { label: "查看物业照片", to: "act1_trial_property_pickup" },
      { label: "顺着论坛继续看", to: "act1_trial_anonymous_forum" },
    ],
  },
  {
    id: "act1_trial_property_pickup",
    title: "Property Pickup",
    purpose: "Show the property desk as an administrative end of the relationship.",
    speaker: "旁白",
    mood: "sterile",
    backgroundKey: "lobby-white",
    visualPlaceholder: "Desk, sign form, white bag, bright tile.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_street_aftertaste",
  },
  {
    id: "act1_trial_street_aftertaste",
    title: "Street Aftertaste",
    purpose: "Carry the property scene into street nausea, debt reminder, and emotional residue.",
    speaker: "旁白",
    mood: "sour",
    backgroundKey: "street-humid",
    visualPlaceholder: "Curbside heat, rideshare wait, debt notification.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_rental_return",
  },
  {
    id: "act1_trial_rental_return",
    title: "Rental Return",
    purpose: "Move the story back into the old building and shared apartment hallway.",
    speaker: "旁白",
    mood: "compressed",
    backgroundKey: "rental-stairs",
    visualPlaceholder: "Broken stair light, shoe row, hallway cat.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_room_cleanup",
  },
  {
    id: "act1_trial_room_cleanup",
    title: "Room Cleanup",
    purpose: "Reduce the room scene to isolation, messages cleared, and search intent.",
    speaker: "苏明",
    mood: "lonely",
    backgroundKey: "rental-room",
    visualPlaceholder: "Single bed, desk lamp, instant noodles, empty chat list.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_anonymous_forum",
  },
  {
    id: "act1_trial_anonymous_forum",
    title: "Anonymous Forum",
    purpose: "Turn private shame into a cleaner anonymous forum path about buying a machine.",
    speaker: "旁白",
    mood: "drawn-in",
    backgroundKey: "forum-clean",
    visualPlaceholder: "White forum UI, anonymous posts, careful parameter lists.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    choices: [
      { label: "点进购买链接", to: "act1_trial_product_page" },
      { label: "回到论坛提示页", to: "act1_trial_forum_hint", kind: "return" },
    ],
  },
  {
    id: "act1_trial_product_page",
    title: "Product Page",
    purpose:
      "Present the polished sales page and modular pitch without turning it into final copy.",
    speaker: "旁白",
    mood: "fixated",
    backgroundKey: "product-page",
    visualPlaceholder: "Clean spec page, module list, gray-blue buttons.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    choices: [
      { label: "打开演示对话", to: "act1_trial_demo_reply" },
      { label: "回到论坛参数帖", to: "act1_trial_anonymous_forum", kind: "return" },
    ],
  },
  {
    id: "act1_trial_demo_reply",
    title: "Demo Reply",
    purpose: "Echo the exact line from work through the product demo preview.",
    speaker: "系统演示",
    mood: "uncanny",
    backgroundKey: "product-demo",
    visualPlaceholder: "Embedded chat preview, mirrored line, quiet room.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    autoNext: "act1_trial_order_form",
  },
  {
    id: "act1_trial_order_form",
    title: "Order Form",
    purpose: "Reduce checkout to installment choice, stale emergency contact, and hesitation.",
    speaker: "旁白",
    mood: "cornered",
    backgroundKey: "order-form",
    visualPlaceholder: "Installment toggle, old contact field, blue helper text.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
    choices: [
      { label: "保留旧联系人并支付", to: "act1_trial_payment" },
      { label: "返回产品页再想想", to: "act1_trial_product_page", kind: "return" },
    ],
  },
  {
    id: "act1_trial_payment",
    title: "Payment",
    purpose: "End the trial pipeline on the irreversible payment beat.",
    speaker: "旁白",
    mood: "committed",
    backgroundKey: "payment-confirm",
    visualPlaceholder: "Bank success prompt, final line still glowing above.",
    noncanonical: true,
    source: "chapter-01-trial-pipeline-dummy",
  },
];
