import type { PrototypeSceneCard } from "@supaluv/shared/story-map";

/** Presentation-only; topology lives in Ink. Source: supa-luv-v2-2026-07 ch02. */
export const draftCh02Scenes = [
  {
    id: "dch02_s001",
    title: "有用。苏明站在收银台后头，视线已经跟了那孩子有一阵了。她在辣",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "有用。苏明站在收银台后头，视线已经跟了那孩子有一阵了。她在辣",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    stageMotion: "slow_push",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s002",
    title: "这是你第三次了。”小女孩先不说话。她抬起头看他，神情平静得不",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "这是你第三次了。”小女孩先不说话。她抬起头看他，神情平静得不",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_barcode_sweep",
    title: "收银台练习 1/3 · 临期辣条。",
    purpose: "Story-native interaction beat.",
    visualPlaceholder: "收银台练习 1/3 · 临期辣条。",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s003",
    title: "苏明刚想接话，小女孩嘴一撇，两颗泪挤了出来，嘴角还没完全垮下",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明刚想接话，小女孩嘴一撇，两颗泪挤了出来，嘴角还没完全垮下",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s004",
    title: "苏明看着她。她回看他，眼神又变回了那种平静的。等他想明白发生",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明看着她。她回看他，眼神又变回了那种平静的。等他想明白发生",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s005",
    title: "苏明快追上了。小女孩脚步一停，站在原地，哇地嚎啕大哭，嗓门比",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明快追上了。小女孩脚步一停，站在原地，哇地嚎啕大哭，嗓门比",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s006",
    title: "苏明往旁边跳，折叠椅擦着他耳边过去，带起一阵风。他赶紧把手机",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明往旁边跳，折叠椅擦着他耳边过去，带起一阵风。他赶紧把手机",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s007",
    title: "大妈把小女孩搂进怀里，给大胖子使了个眼色。大胖子把折叠椅放下",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "大妈把小女孩搂进怀里，给大胖子使了个眼色。大胖子把折叠椅放下",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s008",
    title: "周围的人也都跟着看过去。小女孩被这么多双眼睛盯着，哭声慢慢停",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "周围的人也都跟着看过去。小女孩被这么多双眼睛盯着，哭声慢慢停",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s009",
    title: "苏明反射性就扑了过去。他没注意脚下。大胖子刚才放下的折叠椅就",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明反射性就扑了过去。他没注意脚下。大胖子刚才放下的折叠椅就",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s010",
    title: "等他抬起头，小女孩早就不见了。大胖子收起折叠椅，一脸说不清是",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "等他抬起头，小女孩早就不见了。大胖子收起折叠椅，一脸说不清是",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s011",
    title: "苏明正想说什么，货架那头绕出来一个人。雷欧，背着包，背着手，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明正想说什么，货架那头绕出来一个人。雷欧，背着包，背着手，",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s012",
    title: "雷欧骑的是一辆蓝色小电驴，车把手上绑着一圈快递贴纸，不知道从",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "雷欧骑的是一辆蓝色小电驴，车把手上绑着一圈快递贴纸，不知道从",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s013",
    title: "苏明：“踏实个屁。”“不踏实，但干净。”石家小楼在一条旧巷子",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明：“踏实个屁。”“不踏实，但干净。”石家小楼在一条旧巷子",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s014",
    title: "雷欧按门铃。没反应。两人站在门口，等。等了大概十分钟，雷欧从",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "雷欧按门铃。没反应。两人站在门口，等。等了大概十分钟，雷欧从",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s015",
    title: "石佩欣出来——睡衣，头发随手扎着，发卡还没拔，露出一截橡皮鸭",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "石佩欣出来——睡衣，头发随手扎着，发卡还没拔，露出一截橡皮鸭",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s016",
    title: "对，还兼职别的。”“只要别在我楼里摆摊。”她一点不绕弯子，抽",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "对，还兼职别的。”“只要别在我楼里摆摊。”她一点不绕弯子，抽",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s017",
    title: "不抽。不带。”苏明顿了顿，硬着头皮往下说，“分了，我提的。”",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "不抽。不带。”苏明顿了顿，硬着头皮往下说，“分了，我提的。”",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_housing_hotspots",
    title: "看房标注 1/3 · 墙皮。",
    purpose: "Story-native interaction beat.",
    visualPlaceholder: "看房标注 1/3 · 墙皮。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s018",
    title: "假设也不行。”猫这时候从屋里踱出来，跳下门槛，顺道踩了苏明一",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "假设也不行。”猫这时候从屋里踱出来，跳下门槛，顺道踩了苏明一",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s019",
    title: "雷欧在旁边没动，停了一会儿，很轻地说了一句：“她又开了一局。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "雷欧在旁边没动，停了一会儿，很轻地说了一句：“她又开了一局。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s020",
    title: "门外站着个抱保温杯的大爷，一脸急切：“娃儿，你是不是新搬来的",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "门外站着个抱保温杯的大爷，一脸急切：“娃儿，你是不是新搬来的",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s021",
    title: "石佩欣天天憋在2F，外卖吃了三个月，公共区出没时间固定在深夜",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "石佩欣天天憋在2F，外卖吃了三个月，公共区出没时间固定在深夜",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s022",
    title: "不知道。我也没懂。”“她觉得，”雷欧说，停了一下，“那个机器",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "不知道。我也没懂。”“她觉得，”雷欧说，停了一下，“那个机器",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s023",
    title: "苏明以为是那种钢铁感的、关节明显的那种，看了一眼才发现不是—",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明以为是那种钢铁感的、关节明显的那种，看了一眼才发现不是—",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s024",
    title: "苏明把手机推回去：“测那玩意儿的都有病。”“你们中文场不也全",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明把手机推回去：“测那玩意儿的都有病。”“你们中文场不也全",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s025",
    title: "他把手机翻面扣着，不理他。雷欧说，他其实想报名，但女友觉得这",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他把手机翻面扣着，不理他。雷欧说，他其实想报名，但女友觉得这",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s026",
    title: "他把话题关了，不想多说。当天晚上，苏明一个人坐在3F-A，手",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他把话题关了，不想多说。当天晚上，苏明一个人坐在3F-A，手",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s027",
    title: "他划开手机上的交友软件消磨时间：一个简介写着“社恐找懂我的人",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他划开手机上的交友软件消磨时间：一个简介写着“社恐找懂我的人",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s028",
    title: "页面再往下滑，是体验官评价区。五星那条底下写着：“自从有了她",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "页面再往下滑，是体验官评价区。五星那条底下写着：“自从有了她",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_mobile_questionnaire",
    title: "手机问卷 1/3 · 邻居容忍度。",
    purpose: "Story-native interaction beat.",
    visualPlaceholder: "手机问卷 1/3 · 邻居容忍度。",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s029",
    title: "公共走廊的路由器就在3F楼梯口旁边，苏明知道这个。石佩欣今晚",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "公共走廊的路由器就在3F楼梯口旁边，苏明知道这个。石佩欣今晚",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s030",
    title: "五分钟后，楼梯口又有声音。石佩欣又上来了——路由器重启完了要",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "五分钟后，楼梯口又有声音。石佩欣又上来了——路由器重启完了要",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s031",
    title: "他想了想，上传了。问卷：邻居容忍度自评——他先填了“一般”，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他想了想，上传了。问卷：邻居容忍度自评——他先填了“一般”，",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch02_s032",
    title: "深夜十一点四十分，他按下了提交。三分钟后，短信回来了：“初审",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "深夜十一点四十分，他按下了提交。三分钟后，短信回来了：“初审",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "d2_chapter_end",
    title: "短信屏幕还亮着。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "短信屏幕还亮着。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
] as const satisfies readonly PrototypeSceneCard[];
