import type { PrototypeSceneCard } from "@supaluv/shared/story-map";

/** Presentation-only; topology lives in Ink. Source: supa-luv-v2-2026-07 ch03. */
export const draftCh03Scenes = [
  {
    id: "dch03_s001",
    title: "匹配问卷来的时候，苏明正在超市收银台后头扫二维码。手机屏幕点",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "匹配问卷来的时候，苏明正在超市收银台后头扫二维码。手机屏幕点",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    stageMotion: "slow_push",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s002",
    title: "他最终没有点开相册图标。选了基础脸17号，用手指一点一点往下",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他最终没有点开相册图标。选了基础脸17号，用手指一点一点往下",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s003",
    title: "苏明看了看屏幕上那张还在预览中的脸，又看了看微信里这个名字，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明看了看屏幕上那张还在预览中的脸，又看了看微信里这个名字，",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    aiBranch: {
      enabled: true,
      waitLabel: "灵感生成中…",
      rejoinSceneId: "dch03_mobile_questionnaire",
      maxAiBeats: 2,
      context:
        "机器人定制页选脸环节：作者两支是「选基础脸别开相册」和「手指在相册上停太久」。请给黑色喜剧第三条：更自欺欺人的操作（比如把模板脸往某个方向微调又不承认），不色情。短选项文案+1-2句对白后必须回到问卷流程。",
      artPool: ["bg-product-page", "bg-rental-room"],
      portraitPool: [
        "suming-shame",
        "suming-tempted",
        "suming-restless",
        "suming-uncanny",
      ],
      speakerPool: ["苏明", "旁白"],
    },
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_mobile_questionnaire",
    title: "手机问卷 1/3 · 邻居容忍度。",
    purpose: "Story-native interaction beat.",
    visualPlaceholder: "手机问卷 1/3 · 邻居容忍度。",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s004",
    title: "他把“记仇时长”的滑块往永久拖了一下，又默默拖了回来，停在零",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他把“记仇时长”的滑块往永久拖了一下，又默默拖了回来，停在零",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s005",
    title: "苏明把感官偏好那页提交了，然后回陈佳：“行，傍晚。”陈佳来的",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明把感官偏好那页提交了，然后回陈佳：“行，傍晚。”陈佳来的",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s006",
    title: "两个人都没先走，都在等对方先走。巷子里这个时间有点吵，有人推",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "两个人都没先走，都在等对方先走。巷子里这个时间有点吵，有人推",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s007",
    title: "《对外统一口径建议话术》，三选一：美术用品、健身假人、医疗康",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "《对外统一口径建议话术》，三选一：美术用品、健身假人、医疗康",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s008",
    title: "三天后货物恢复派送。到货那天，苏明跟老板娘谎称亲戚来，请了半",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "三天后货物恢复派送。到货那天，苏明跟老板娘谎称亲戚来，请了半",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s009",
    title: "纸箱上印着“健身假人 / 模特道具”，字大得生怕别人看不见—",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "纸箱上印着“健身假人 / 模特道具”，字大得生怕别人看不见—",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s010",
    title: "初中女生三个人扶着中间那只箱子，配合着往上挪，苏明踩在她们前",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "初中女生三个人扶着中间那只箱子，配合着往上挪，苏明踩在她们前",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s011",
    title: "苏明站在半截楼梯上，一手扶着箱子，一手把那只手往里按，来不及",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明站在半截楼梯上，一手扶着箱子，一手把那只手往里按，来不及",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s012",
    title: "雷欧从苏明身边往楼梯口慢慢挪了一步，眼神往巷口方向瞄了一下，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "雷欧从苏明身边往楼梯口慢慢挪了一步，眼神往巷口方向瞄了一下，",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s013",
    title: "不到五分钟，黄老太循声从巷口走过来了，手机已经打出去了，是网",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "不到五分钟，黄老太循声从巷口走过来了，手机已经打出去了，是网",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "黄老太",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s014",
    title: "苏明点了点头。警察又扬了扬眉毛。意思还是很明显。苏明又点了点",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明点了点头。警察又扬了扬眉毛。意思还是很明显。苏明又点了点",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "警察",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s015",
    title: "苏明：“警官，我能看懂。但我需要你明说，我才有合理的解释给你",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明：“警官，我能看懂。但我需要你明说，我才有合理的解释给你",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s016",
    title: "第三只箱子他只扫了一眼人头的部分，低头在本子上记了什么，然后",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "第三只箱子他只扫了一眼人头的部分，低头在本子上记了什么，然后",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s017",
    title: "僵住了，谁都没先动。石佩欣从楼上走下来。她在楼道里看了一圈，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "僵住了，谁都没先动。石佩欣从楼上走下来。她在楼道里看了一圈，",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "shipeixin-calm-smile",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "calm-smile",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s018",
    title: "网格员小袁耳根发红，往后退了半步。三个初中女生对视了一眼，悄",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "网格员小袁耳根发红，往后退了半步。三个初中女生对视了一眼，悄",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "网格员",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s019",
    title: "石佩欣抱着头，在楼道灯下端详了两秒：“做工不错，挺像真人的。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "石佩欣抱着头，在楼道灯下端详了两秒：“做工不错，挺像真人的。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "shipeixin-guarded",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "guarded",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s020",
    title: "苏明：“……不清楚，代收的，亲戚公司的。”“代收还分三箱。”",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明：“……不清楚，代收的，亲戚公司的。”“代收还分三箱。”",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    companionPortraitKey: "shipeixin-guarded",
    companionSpeaker: "石佩欣",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s021",
    title: "你敢。房租预付了。”窗外恰好飘进来黄老太的一句话，隔着好几户",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "你敢。房租预付了。”窗外恰好飘进来黄老太的一句话，隔着好几户",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "黄老太",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s022",
    title: "我能帮开箱吗？”“不用，出去。”“万一是炸——”“不是炸弹。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "我能帮开箱吗？”“不用，出去。”“万一是炸——”“不是炸弹。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_robot_barcode",
    title: "开箱激活 1/3 · 主机箱外激活码。",
    purpose: "Story-native interaction beat.",
    visualPlaceholder: "开箱激活 1/3 · 主机箱外激活码。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s023",
    title: "苏明对着说明书准备自己拼，石佩欣站在门口看了一会儿，说她朋友",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明对着说明书准备自己拼，石佩欣站在门口看了一会儿，说她朋友",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s024",
    title: "苏明的手指找到后颈那个位置，指腹压上去，在心里开始数：一，二",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明的手指找到后颈那个位置，指腹压上去，在心里开始数：一，二",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s025",
    title: "数到三，手又缩了回来。石佩欣看着他，没说话。苏明深吸一口气，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "数到三，手又缩了回来。石佩欣看着他，没说话。苏明深吸一口气，",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "shipeixin-guarded",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "guarded",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s026",
    title: "睫毛先动，然后是眼睑，然后是瞳孔在灯光下对好焦。停了大约两秒",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "睫毛先动，然后是眼睑，然后是瞳孔在灯光下对好焦。停了大约两秒",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s027",
    title: "它说出了那个名字。陈佳。两个字，被一台机器的嘴说出来，停在屋",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "它说出了那个名字。陈佳。两个字，被一台机器的嘴说出来，停在屋",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s028",
    title: "苏明：“……就随便取的。”机器人朱珠看着他，专注得不像机器的",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明：“……就随便取的。”机器人朱珠看着他，专注得不像机器的",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "朱珠",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s029",
    title: "你能不能不把我当替代品，而是当成真正一个人？”她盯着他，等他",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "你能不能不把我当替代品，而是当成真正一个人？”她盯着他，等他",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    companionPortraitKey: "shipeixin-hurt",
    companionSpeaker: "石佩欣",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch03_s030",
    title: "机器人朱珠看着他，嘴角动了一下，像是满意。“好。那今天，我会",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "机器人朱珠看着他，嘴角动了一下，像是满意。“好。那今天，我会",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "朱珠",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "d3_chapter_end",
    title: "屋子里就剩他们两个，一个人，一台机器，和一盏灯。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "屋子里就剩他们两个，一个人，一台机器，和一盏灯。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
] as const satisfies readonly PrototypeSceneCard[];
