import type { PrototypeSceneCard } from "@supaluv/shared/story-map";

/** Presentation-only; topology lives in Ink. */
export const draftCh02Scenes = [
  {
    id: "dch02_s001",
    title: "第二章 她不会评判你",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "第二章 她不会评判你",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    stageMotion: "slow_push",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s002",
    title: "苏明当晚在快捷酒店将就了一宿，一百六一晚，躺在陌",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明当晚在快捷酒店将就了一宿，一百六一晚，躺在陌",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s003",
    title: "这份工是他自己找上门的。当时门口贴着一张招工启事",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "这份工是他自己找上门的。当时门口贴着一张招工启事",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "老板娘",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s004",
    title: "这天，他就撞上了后一件事。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "这天，他就撞上了后一件事。",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s005",
    title: '苏明从收银台后头绕出来，一把按住那孩子的手腕："',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明从收银台后头绕出来，一把按住那孩子的手腕："',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s006",
    title: '小孩"哇"地一声就哭了出来——这哭声比动作还快，',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '小孩"哇"地一声就哭了出来——这哭声比动作还快，',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s007",
    title: '"那也是你逼的！他手滑！"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"那也是你逼的！他手滑！"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "老板娘",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s008",
    title: '"辣条钱我扫了。"苏明没搭理老板娘的劝，转身回到',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"辣条钱我扫了。"苏明没搭理老板娘的劝，转身回到',
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "老板娘",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s009",
    title: "那母亲骂骂咧咧地拽着孩子往外走，临出门还啐了一句",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "那母亲骂骂咧咧地拽着孩子往外走，临出门还啐了一句",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "老板娘",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s010",
    title: '"我出。"他说了两遍，脸绷得紧紧的，话说得硬邦邦',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"我出。"他说了两遍，脸绷得紧紧的，话说得硬邦邦',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s011",
    title: "傍晚，看房的时间到了。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "傍晚，看房的时间到了。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s012",
    title: "门开了。石佩欣穿着一件皮卡丘图案的家居服，身后的",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "门开了。石佩欣穿着一件皮卡丘图案的家居服，身后的",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s013",
    title: '"对，还兼职别的。"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"对，还兼职别的。"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s014",
    title: '问到"分手谁提的"这一句，热心过头的雷欧凑了过来',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '问到"分手谁提的"这一句，热心过头的雷欧凑了过来',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s015",
    title: '"不抽。不带。分了，"苏明顿了顿，硬着头皮往下说',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"不抽。不带。分了，"苏明顿了顿，硬着头皮往下说',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s016",
    title: "雷欧在她身后偷偷竖起大拇指，被一个眼神精准地扫到",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "雷欧在她身后偷偷竖起大拇指，被一个眼神精准地扫到",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s017",
    title: '"你再交三个月房租，这墙就能补上。"石佩欣白了他',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"你再交三个月房租，这墙就能补上。"石佩欣白了他',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s018",
    title: '苏明这人嘴皮子有时比脑子还快："能不能——假设—',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明这人嘴皮子有时比脑子还快："能不能——假设—',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s019",
    title: '"你不是刚分？"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"你不是刚分？"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s020",
    title: '"假设也不行。"她挥了挥手，"我这楼的规矩比你那',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"假设也不行。"她挥了挥手，"我这楼的规矩比你那',
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s021",
    title: '雷欧小声嘀咕："她是不是在说我？"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧小声嘀咕："她是不是在说我？"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s022",
    title: "当夜，苏明就搬进来住下了。行李是几个垃圾袋的升级",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "当夜，苏明就搬进来住下了。行李是几个垃圾袋的升级",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s023",
    title: '苏明心里"咯噔"一下——第一反应是石佩欣反悔了，',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明心里"咯噔"一下——第一反应是石佩欣反悔了，',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s024",
    title: "苏明愣了两秒，才想起自己确实不知道，也确实不该知",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明愣了两秒，才想起自己确实不知道，也确实不该知",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s025",
    title: '雷欧帮着抬了半程行李，走到门口忽然刹住了脚步："',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧帮着抬了半程行李，走到门口忽然刹住了脚步："',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s026",
    title: '"攒什么？"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"攒什么？"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s027",
    title: '雷欧比划了两根手指："两份工，you crazy',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧比划了两根手指："两份工，you crazy',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s028",
    title: '"Robot。"雷欧压低了声音，眼睛瞪得溜圆，"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"Robot。"雷欧压低了声音，眼睛瞪得溜圆，"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s029",
    title: '"我？"雷欧像是被烫到了似的，往后一缩，"宿舍住',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"我？"雷欧像是被烫到了似的，往后一缩，"宿舍住',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s030",
    title: '雷欧耸了耸肩："你们中文场不也全天候被听？一样一',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧耸了耸肩："你们中文场不也全天候被听？一样一',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s031",
    title: '"上班，"雷欧点点头，一本正经地反驳，"他们也说',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"上班，"雷欧点点头，一本正经地反驳，"他们也说',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s032",
    title: "躺上新床板，巷子里传来称重的声音和讨价还价的声音",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "躺上新床板，巷子里传来称重的声音和讨价还价的声音",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s033",
    title: "他又点开大学室友的对话框，想找个人说说话，翻了半",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他又点开大学室友的对话框，想找个人说说话，翻了半",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s034",
    title: '他划开手机上的交友软件消磨时间：一个简介写着"社',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '他划开手机上的交友软件消磨时间：一个简介写着"社',
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s035",
    title: '落地页第一行字迎面撞过来："她不会评判你，只会理',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '落地页第一行字迎面撞过来："她不会评判你，只会理',
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s036",
    title: "页面再往下滑，是体验官评价区。五星那条底下写着：",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "页面再往下滑，是体验官评价区。五星那条底下写着：",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s037",
    title: "问卷比他想象中要正经得多：上传居住环境照片——他",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "问卷比他想象中要正经得多：上传居住环境照片——他",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s038",
    title: "苏明想起这楼里住着三个活人，还有一只猫，手指在屏",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明想起这楼里住着三个活人，还有一只猫，手指在屏",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s039",
    title: '三分钟后，短信回来了："初审通过。请于48小时内',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '三分钟后，短信回来了："初审通过。请于48小时内',
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s040",
    title: '苏明盯着这条短信看了半分钟，喃喃说了句："就当我',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明盯着这条短信看了半分钟，喃喃说了句："就当我',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "d2_chapter_end",
    title: "初审通过",
    purpose: "Chapter terminal beat.",
    visualPlaceholder: "苏明盯着这条短信看了半分钟，喃喃说了句：「就当我",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-committed",
    bgmKey: "chapter-end",
    sfxKey: "notify-soft",
    speaker: "苏明",
    mood: "committed",
    noncanonical: true,
    source: "draft-2026-07",
  },
] as const satisfies readonly PrototypeSceneCard[];
