import type { PrototypeSceneCard } from "@supaluv/shared/story-map";

/** Presentation-only; topology lives in Ink. */
export const draftCh02Scenes = [
  {
    id: "dch02_s001",
    title: "第二章 她不会评判你",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "第二章 她不会评判你",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    stageMotion: "slow_push",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s002",
    title: "苏明当晚在快捷酒店将就了一宿，一百六一晚，躺在陌",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明当晚在快捷酒店将就了一宿，一百六一晚，躺在陌",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s003",
    title: "这份工是他靠一分钟扫四十件抢来的。老板娘姓周，说",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "这份工是他靠一分钟扫四十件抢来的。老板娘姓周，说话难听，",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "老板娘",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_barcode_sweep",
    title: "条码连扫",
    purpose: "Story-native barcode sweep interaction.",
    visualPlaceholder: "条码连扫练习",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s004",
    title: "这天，他就撞上了后一件事。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "这天，他就撞上了后一件事。",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s005",
    title: '苏明从收银台后头绕出来，一把按住那孩子的手腕："',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明从收银台后头绕出来，一把按住那孩子的手腕："',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s006",
    title: '小孩"哇"地一声就哭了出来——这哭声比动作还快，',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '小孩"哇"地一声就哭了出来——这哭声比动作还快，',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s007",
    title: '"那也是你逼的！他手滑！"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"那也是你逼的！他手滑！"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "老板娘",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s008",
    title: '"辣条钱我扫了。"苏明没搭理老板娘的劝，转身回到',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"辣条钱我扫了。"苏明没搭理老板娘的劝，转身回到',
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "老板娘",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s009",
    title: "那母亲骂骂咧咧地拽着孩子往外走，临出门还啐了一句",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "那母亲骂骂咧咧地拽着孩子往外走，临出门还啐了一句",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "老板娘",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s010",
    title: '"我出。"他说第二遍时，脸绷得像在替两包辣条签担',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"我出。"他说第二遍时，脸绷得像在替两包辣条签担保。',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s011",
    title: "傍晚，看房的时间到了。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "傍晚，看房的时间到了。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s012",
    title: "门开了。石佩欣穿着皮卡丘家居服，身后电脑上的图被",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "门开了。石佩欣穿着皮卡丘家居服，身后电脑上的图被她一键缩",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s013",
    title: '"对，还兼职别的。"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"对，还兼职别的。"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s014",
    title: '问到"分手谁提的"这一句，热心过头的雷欧凑了过来',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '问到"分手谁提的"这一句，热心过头的雷欧凑了过来',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s015",
    title: '"不抽。不带。分了，"苏明顿了顿，硬着头皮往下说',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"不抽。不带。分了，"苏明顿了顿，硬着头皮往下说',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s016",
    title: "雷欧在她身后偷偷竖起大拇指，被一个眼神精准地扫到",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "雷欧在她身后偷偷竖起大拇指，被一个眼神精准地扫到",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_housing_hotspots",
    title: "看房热点",
    purpose: "Story-native housing hotspot interaction.",
    visualPlaceholder: "看房热点标注",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s017",
    title: '"你再交三个月房租，这墙就能补上。"石佩欣白了他',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"你再交三个月房租，这墙就能补上。"石佩欣白了他',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s018",
    title: '苏明这人嘴皮子有时比脑子还快："能不能——假设—',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明这人嘴皮子有时比脑子还快："能不能——假设—',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s019",
    title: '"你不是刚分？"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"你不是刚分？"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s020",
    title: '"假设也不行。"她挥手，"我这楼的规矩比你那超市',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"假设也不行。"她挥手，"我这楼的规矩比你那超市严。"打',
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s021",
    title: '雷欧小声嘀咕："她是不是在说我？"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧小声嘀咕："她是不是在说我？"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s022",
    title: "当夜，苏明搬了进来。行李是几个垃圾袋的升级版。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "当夜，苏明搬了进来。行李是几个垃圾袋的升级版。",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s023",
    title: "苏明以为石佩欣反悔，手忙脚乱把东西塞回袋子才开门",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明以为石佩欣反悔，手忙脚乱把东西塞回袋子才开门。门外只",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "石佩欣",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s024",
    title: '"不晓得。我今天刚来。"大爷骂骂咧咧下楼找别人。',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"不晓得。我今天刚来。"大爷骂骂咧咧下楼找别人。苏明关门',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s025",
    title: '雷欧帮着抬了半程行李，走到门口忽然刹住了脚步："',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧帮着抬了半程行李，走到门口忽然刹住了脚步："',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s026",
    title: '"攒什么？"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"攒什么？"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s027",
    title: '雷欧比划两根手指："两份工，you crazy。',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧比划两根手指："两份工，you crazy。"他掏出',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s028",
    title: '"Robot。"雷欧压低了声音，眼睛瞪得溜圆，"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"Robot。"雷欧压低了声音，眼睛瞪得溜圆，"',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s029",
    title: '"我？"雷欧往后一缩，"宿舍住不下。机器人晚上睁',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"我？"雷欧往后一缩，"宿舍住不下。机器人晚上睁眼怎么办',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s030",
    title: '雷欧耸了耸肩："你们中文场不也全天候被听？一样一',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧耸了耸肩："你们中文场不也全天候被听？一样一',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s031",
    title: '"上班，"雷欧点点头，一本正经地反驳，"他们也说',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"上班，"雷欧点点头，一本正经地反驳，"他们也说',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s032",
    title: "躺上新床板，巷子里有人称重、讨价，隔壁回锅肉的油",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "躺上新床板，巷子里有人称重、讨价，隔壁回锅肉的油烟钻进来",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s033",
    title: "他点开大学室友的对话框，最后一条是三个月前的婚礼",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他点开大学室友的对话框，最后一条是三个月前的婚礼请柬。输",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s034",
    title: '他划开手机上的交友软件消磨时间：一个简介写着"社',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '他划开手机上的交友软件消磨时间：一个简介写着"社',
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s035",
    title: '落地页第一行字迎面撞过来："她不会评判你，只会理',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '落地页第一行字迎面撞过来："她不会评判你，只会理',
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s036",
    title: '评价区五星第一条写着："自从有了她，我再也不用假',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '评价区五星第一条写着："自从有了她，我再也不用假装很好。',
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s037",
    title: "问卷正经得过分：上传居住环境，他只拍没掉墙皮的死",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "问卷正经得过分：上传居住环境，他只拍没掉墙皮的死角；邻居",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_mobile_questionnaire",
    title: "手机问卷",
    purpose: "Story-native mobile questionnaire interaction.",
    visualPlaceholder: "体验官手机问卷",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s038",
    title: "苏明想起这楼里住着三个活人，还有一只猫，手指在屏",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明想起这楼里住着三个活人，还有一只猫，手指在屏",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s039",
    title: '三分钟后，短信回来了："初审通过。请于48小时内',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '三分钟后，短信回来了："初审通过。请于48小时内',
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch02_s040",
    title: '苏明盯着这条短信看了半分钟，喃喃说了句："就当我',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明盯着这条短信看了半分钟，喃喃说了句："就当我',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "lonely-pad",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "d2_chapter_end",
    title: "初审通过",
    purpose: "Chapter terminal beat.",
    visualPlaceholder: "短信屏幕还亮着。",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    portraitKey: "suming-committed",
    bgmKey: "chapter-end",
    sfxKey: "notify-soft",
    speaker: "苏明",
    mood: "committed",
    noncanonical: true,
    source: "draft-2026-07",
  },
] as const satisfies readonly PrototypeSceneCard[];
