import type { PrototypeSceneCard } from "@supaluv/shared/story-map";

/** Presentation-only; topology lives in Ink. */
export const draftCh01Scenes = [
  {
    id: "dch01_s001",
    title: "第一章 你有病吧",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "第一章 你有病吧",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    stageMotion: "slow_push",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "工作人员",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_emotion_calibration",
    title: "情绪样本校准",
    purpose: "Story-native emotion calibration interaction.",
    visualPlaceholder: "客服系统 · 情绪样本校准",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s002",
    title: "协议贴在门后头，字号小得跟藏起来似的，得凑近了眯",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "协议贴在门后头，字号小得跟藏起来似的，得凑近了眯",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_protocol_test",
    title: "协议条款校对",
    purpose: "Story-native protocol clause interaction.",
    visualPlaceholder: "协议条款校对",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s003",
    title: "工作人员愣了半秒，随即笑意深了一层，像是遇上了识",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "工作人员愣了半秒，随即笑意深了一层，像是遇上了识",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "工作人员",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s004",
    title: "这话苏明听完，心里那点疑虑没散，倒是多了一层新的",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "这话苏明听完，心里那点疑虑没散，倒是多了一层新的",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "AI",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s005",
    title: "苏明往椅背上一靠，语气跟报快递单号差不多，平平的",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明往椅背上一靠，语气跟报快递单号差不多，平平的",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "AI",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s006",
    title: '"评判不评判的，"苏明盯着平板角落那几条进度条—',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"评判不评判的，"苏明盯着平板角落那几条进度条—',
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s007",
    title: '这也不是他头一回测。上个月他刚测过一场"职场受气',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '这也不是他头一回测。上个月他刚测过一场"职场受气',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s008",
    title: "耳机线绕在支架上晃悠，一个戴降噪耳罩的姑娘正拆开",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "耳机线绕在支架上晃悠，一个戴降噪耳罩的姑娘正拆开",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s009",
    title: "走廊椅子上坐着个外国小伙，二十出头，书包还没卸下",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "走廊椅子上坐着个外国小伙，二十出头，书包还没卸下",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s010",
    title: '"不是那种早就没话讲的分手。"他说，声音低了一些',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"不是那种早就没话讲的分手。"他说，声音低了一些',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s011",
    title: "昨晚吃完饭，两个人抢最后一块排骨，酱汁蹭到陈佳嘴",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "昨晚吃完饭，两个人抢最后一块排骨，酱汁蹭到陈佳嘴",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s012",
    title: "进行到一半，他低下头，碰了碰陈佳的脚，鬼使神差地",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "进行到一半，他低下头，碰了碰陈佳的脚，鬼使神差地",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s013",
    title: "不是尖叫，也不是那种当场要报警的架势。是真扫兴，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "不是尖叫，也不是那种当场要报警的架势。是真扫兴，",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s014",
    title: '"就一下。"苏明还想圆。',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"就一下。"苏明还想圆。',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s015",
    title: '"我就是……"他张了张嘴，一个字都没接上来。十六',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"我就是……"他张了张嘴，一个字都没接上来。十六',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s016",
    title: "苏明那点死要面子的劲儿，偏偏在这个时候冒了头——",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明那点死要面子的劲儿，偏偏在这个时候冒了头——",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s017",
    title: "空气僵了两秒钟，谁都没再说话。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "空气僵了两秒钟，谁都没再说话。",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s018",
    title: "门关上，反锁的声音清清楚楚传过来，跟平时吵完架故",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "门关上，反锁的声音清清楚楚传过来，跟平时吵完架故",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s019",
    title: "装到后半夜，他才慢慢想明白：这台阶是他自己拆的，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "装到后半夜，他才慢慢想明白：这台阶是他自己拆的，",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s020",
    title: "没有当众处刑，也没有闪送三连虐，就这么淡淡一句，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "没有当众处刑，也没有闪送三连虐，就这么淡淡一句，",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s021",
    title: '"你听起来在硬撑。"AI 忽然说，"是不是在假装',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"你听起来在硬撑。"AI 忽然说，"是不是在假装',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "AI",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s022",
    title: '"你刚才那句话，比你前面的话慢了零点四秒。"AI',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"你刚才那句话，比你前面的话慢了零点四秒。"AI',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s023",
    title: "想明白这一层，他反而自在了点。跟一把尺子较什么劲",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "想明白这一层，他反而自在了点。跟一把尺子较什么劲",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s024",
    title: '"那你一定很难过，难过的时候更需要被抱一抱……"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"那你一定很难过，难过的时候更需要被抱一抱……"',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s025",
    title: '苏明手指一点，把它关掉："别弹了，任务听到这儿就',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明手指一点，把它关掉："别弹了，任务听到这儿就',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s026",
    title: '苏明差点笑出声来："行吧，你赢了，我很脆弱，满意',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '苏明差点笑出声来："行吧，你赢了，我很脆弱，满意',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s027",
    title: '隔壁，那姑娘划下一个标签，小声跟同事总结："这条',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '隔壁，那姑娘划下一个标签，小声跟同事总结："这条',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s028",
    title: "雷欧在走廊上听得云里雾里，他的中文水平也就够辨认",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "雷欧在走廊上听得云里雾里，他的中文水平也就够辨认",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s029",
    title: "四目相对，谁都没先开口。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "四目相对，谁都没先开口。",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s030",
    title: '雷欧中文说得不利索，可这股火气不需要语法撑腰："',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧中文说得不利索，可这股火气不需要语法撑腰："',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s031",
    title: "苏明摘下耳机走出来，走廊里几道目光贴上来，粘乎乎",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明摘下耳机走出来，走廊里几道目光贴上来，粘乎乎",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s032",
    title: '休息区那头，一个大姐正对着某间测试门喊："我不是',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '休息区那头，一个大姐正对着某间测试门喊："我不是',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s033",
    title: "没人接话，哄地一下笑着散开了，跟刚看完一场不要钱",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "没人接话，哄地一下笑着散开了，跟刚看完一场不要钱",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s034",
    title: '"Hey——苏？苏明？"雷欧从后头追上来，工牌歪',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"Hey——苏？苏明？"雷欧从后头追上来，工牌歪',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s035",
    title: '"他们听。"雷欧比划着自己的耳朵，中英文夹生地往',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"他们听。"雷欧比划着自己的耳朵，中英文夹生地往',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s036",
    title: '"说好删干净的。"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"说好删干净的。"',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s037",
    title: "苏明转身就往前台走，脚步很快，几乎是小跑。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明转身就往前台走，脚步很快，几乎是小跑。",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "小组长",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s038",
    title: '"合规质检流程，协议第三页写得明白。"对方把平板',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"合规质检流程，协议第三页写得明白。"对方把平板',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s039",
    title: '"我给你们上差评，"苏明急了，声音都拔高了，"打',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"我给你们上差评，"苏明急了，声音都拔高了，"打',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "小组长",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s040",
    title: '"不愿意测，随时可以不来。"小组长的语气始终没起',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"不愿意测，随时可以不来。"小组长的语气始终没起',
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "小组长",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s041",
    title: '雷欧站在他侧后方，下巴一抬，替他撑场："他要谈，',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧站在他侧后方，下巴一抬，替他撑场："他要谈，',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "小组长",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s042",
    title: "就在这时，苏明的手机震了一下。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "就在这时，苏明的手机震了一下。",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s043",
    title: "他捏着手机，盯着这行字看了半天。他刚才在里面卖掉",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他捏着手机，盯着这行字看了半天。他刚才在里面卖掉",
    backgroundKey: "product-page",
    artKey: "bg-product-page",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "小组长",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s044",
    title: "不是怂成一滩泥。他心里明白，这地方今天要是撕破脸",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "不是怂成一滩泥。他心里明白，这地方今天要是撕破脸",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s045",
    title: "雷欧看他这副丧气样，倒想起了自己刚来重庆那阵子：",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "雷欧看他这副丧气样，倒想起了自己刚来重庆那阵子：",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s046",
    title: "听筒里漏出个女声，不耐烦，还带点重庆腔骂人的调调",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "听筒里漏出个女声，不耐烦，还带点重庆腔骂人的调调",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s047",
    title: '"九百，顶天了。"',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"九百，顶天了。"',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s048",
    title: '雷欧对着听筒喊："九百？OK……地址发我，现在。',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '雷欧对着听筒喊："九百？OK……地址发我，现在。',
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s049",
    title: '"今晚能看。石家小楼，那女的嘴很凶，"他想了半天',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"今晚能看。石家小楼，那女的嘴很凶，"他想了半天',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "dch01_s050",
    title: '"先看房。"他打断了雷欧还想往下说的话，"有地方',
    purpose: "Draft adaptation beat.",
    visualPlaceholder: '"先看房。"他打断了雷欧还想往下说的话，"有地方',
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "draft-2026-07",
  },
  {
    id: "d1_chapter_end",
    title: "先看房",
    purpose: "Chapter terminal beat.",
    visualPlaceholder: "苏明盯着导航上那条弯弯曲曲的旧巷子，没吭声，转身",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-committed",
    bgmKey: "chapter-end",
    sfxKey: "notify-soft",
    speaker: "苏明",
    mood: "committed",
    noncanonical: true,
    source: "draft-2026-07",
  },
] as const satisfies readonly PrototypeSceneCard[];
