import type { PrototypeSceneCard } from "@supaluv/shared/story-map";

/** Presentation-only; topology lives in Ink. Source: supa-luv-v2-2026-07 ch01. */
export const draftCh01Scenes = [
  {
    id: "dch01_s001",
    title: "聊天记录测完就删，一个字不留。您说得越真，情绪波动分越高，补",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "聊天记录测完就删，一个字不留。您说得越真，情绪波动分越高，补",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    stageMotion: "slow_push",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "工作人员",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_emotion_calibration",
    title: "校准台载入虚构样本 1/3。",
    purpose: "Story-native interaction beat.",
    visualPlaceholder: "校准台载入虚构样本 1/3。",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s002",
    title: "协议贴在门后头，字号小得跟藏起来似的，得凑近了眯着眼才看得清",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "协议贴在门后头，字号小得跟藏起来似的，得凑近了眯着眼才看得清",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_protocol_test",
    title: "条款校对 1/3 · 原始录音自动清除。",
    purpose: "Story-native interaction beat.",
    visualPlaceholder: "条款校对 1/3 · 原始录音自动清除。",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "系统",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s003",
    title: "工作人员愣了半秒，随即笑意深了一层，像是遇上了识货的：“您这",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "工作人员愣了半秒，随即笑意深了一层，像是遇上了识货的：“您这",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "工作人员",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s004",
    title: "门关上，隔音棉把外头的声音都吸走了，耳机里响起一个女声，声音",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "门关上，隔音棉把外头的声音都吸走了，耳机里响起一个女声，声音",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "AI",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s005",
    title: "这也不是他头一回测。上个月他刚测过一场“职场受气经历”，编了",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "这也不是他头一回测。上个月他刚测过一场“职场受气经历”，编了",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s006",
    title: "耳机那头没有接心疼的话。沉默持续了大概三秒，比预计的长一点。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "耳机那头没有接心疼的话。沉默持续了大概三秒，比预计的长一点。",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s007",
    title: "根据您上次的记录，”AI 说，语气还是那副甜的，但多了一种叫",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "根据您上次的记录，”AI 说，语气还是那副甜的，但多了一种叫",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "AI",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s008",
    title: "您今天的情绪指标存在矛盾。”AI 停了一拍，像是在调取什么档",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "您今天的情绪指标存在矛盾。”AI 停了一拍，像是在调取什么档",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "AI",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s009",
    title: "短促，不含糊，跟敲了颗钉子一样。苏明的手在膝盖上按了按。他心",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "短促，不含糊，跟敲了颗钉子一样。苏明的手在膝盖上按了按。他心",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s010",
    title: "薯片没拆。一个戴降噪耳罩的姑娘跟旁边同事对了个眼神，小声：“",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "薯片没拆。一个戴降噪耳罩的姑娘跟旁边同事对了个眼神，小声：“",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s011",
    title: "……行，我说。”他开口，语气比刚才随意了一些，像是随便聊聊的",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "……行，我说。”他开口，语气比刚才随意了一些，像是随便聊聊的",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    aiBranch: {
      enabled: true,
      waitLabel: "灵感生成中…",
      rejoinSceneId: "dch01_s012",
      maxAiBeats: 2,
      context:
        "苏明在测试间要讲分手：作者两支是「借朋友的壳」和「硬说真实」。请给黑色喜剧第三条：更怂、更绕、更程序员式的自我保护话术，不色情。短选项文案+1-2句对白后必须回到讲述现场。",
      artPool: ["bg-office-night", "bg-lobby-white", "bg-rental-room"],
      portraitPool: [
        "suming-shame",
        "suming-panic",
        "suming-restless",
        "suming-lonely",
        "suming-tempted",
      ],
      speakerPool: ["苏明", "旁白"],
    },
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s012",
    title: "走廊椅子上坐着个外国小伙，二十出头，书包还没卸下来，手里攥着",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "走廊椅子上坐着个外国小伙，二十出头，书包还没卸下来，手里攥着",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s013",
    title: "不是那种早就没话讲的分手。”他说，声音低了一些，“我那个朋友",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "不是那种早就没话讲的分手。”他说，声音低了一些，“我那个朋友",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s014",
    title: "昨晚吃完饭，陈佳先抢到最后一块排骨，拿筷子夹起来举着，像赢了",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "昨晚吃完饭，陈佳先抢到最后一块排骨，拿筷子夹起来举着，像赢了",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s015",
    title: "两个人就着这点收尾的温度往里走。灯没关，也没人去关——那会儿",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "两个人就着这点收尾的温度往里走。灯没关，也没人去关——那会儿",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s016",
    title: "进行到一半，他低下头。他自己也说不清楚是怎么回事，视线落到陈",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "进行到一半，他低下头。他自己也说不清楚是怎么回事，视线落到陈",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s017",
    title: "……你干嘛呢。”她说话了，声音是那种很轻、很慢的调子，好像怕",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "……你干嘛呢。”她说话了，声音是那种很轻、很慢的调子，好像怕",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s018",
    title: "把我脚放开。”苏明松了手。“不是吧——”他想确认一下，“你生",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "把我脚放开。”苏明松了手。“不是吧——”他想确认一下，“你生",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s019",
    title: "隔天吵起来，导火索是一条手机短信。桌上苏明的手机屏幕点亮了，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "隔天吵起来，导火索是一条手机短信。桌上苏明的手机屏幕点亮了，",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s020",
    title: "话越说越多，说着说着陈佳带出了昨晚——“而且你昨天那个……”",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "话越说越多，说着说着陈佳带出了昨晚——“而且你昨天那个……”",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s021",
    title: "你说的就是这个意思！”两个人吵开了，从性癖吵到兼职，从兼职吵",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "你说的就是这个意思！”两个人吵开了，从性癖吵到兼职，从兼职吵",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s022",
    title: "今早他进卧室拿充电器，陈佳脸上没什么表情，只丢下一句：“钥匙",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "今早他进卧室拿充电器，陈佳脸上没什么表情，只丢下一句：“钥匙",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "陈佳",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s023",
    title: "他听起来，”AI 说，“在硬撑。你朋友，现在感觉怎么样？”苏",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "他听起来，”AI 说，“在硬撑。你朋友，现在感觉怎么样？”苏",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "AI",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s024",
    title: "我没法这样评价，”AI 说，“但如果对方还愿意沟通，磨合的空",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "我没法这样评价，”AI 说，“但如果对方还愿意沟通，磨合的空",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "AI",
    mood: "uncanny",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s025",
    title: "工作人员把苏明带到一个小结区，十几把椅子，七八个人已经坐着了",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "工作人员把苏明带到一个小结区，十几把椅子，七八个人已经坐着了",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "工作人员",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s026",
    title: "苏明先生，”她念到这一条，语气没什么变化，“今天讲述了一位朋",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "苏明先生，”她念到这一条，语气没什么变化，“今天讲述了一位朋",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "工作人员",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s027",
    title: "工作人员把平板翻了一下，“协议第三页，现场质检条款——”苏明",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "工作人员把平板翻了一下，“协议第三页，现场质检条款——”苏明",
    backgroundKey: "lobby-white",
    artKey: "bg-lobby-white",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "工作人员",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s028",
    title: "我要见你们负责人。”工作人员说负责人在开会，让他等。苏明等。",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "我要见你们负责人。”工作人员说负责人在开会，让他等。苏明等。",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s029",
    title: "等了大概二十分钟，负责人出来了。他身边站着个外国小伙——书包",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "等了大概二十分钟，负责人出来了。他身边站着个外国小伙——书包",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s030",
    title: "说完，他转身走了。苏明站在原地。那个“双方自愿”落在他嘴边，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "说完，他转身走了。苏明站在原地。那个“双方自愿”落在他嘴边，",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "小组长",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s031",
    title: "补贴到账。金额比平时高了一档，系统附言：情绪波动：优。恭喜升",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "补贴到账。金额比平时高了一档，系统附言：情绪波动：优。恭喜升",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s032",
    title: "旁边有人低低地说了一句：“公司不亏待用心的体验官。”是小组长",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "旁边有人低低地说了一句：“公司不亏待用心的体验官。”是小组长",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "小组长",
    mood: "shame",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s033",
    title: "那个外国小伙从旁边走过来，中文说得很慢，但字很清晰，“我叫雷",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "那个外国小伙从旁边走过来，中文说得很慢，但字很清晰，“我叫雷",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s034",
    title: "不是。”雷欧摇头，“我跟你一样，测试的。但是，”他停了一下，",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "不是。”雷欧摇头，“我跟你一样，测试的。但是，”他停了一下，",
    backgroundKey: "office-night",
    artKey: "bg-office-night",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s035",
    title: "你……找房子？”他问，“今天，你提到了。在里面讲的那个。”苏",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "你……找房子？”他问，“今天，你提到了。在里面讲的那个。”苏",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "dch01_s036",
    title: "我那个楼，”雷欧说，“有一间。不贵，大的。”他掏出手机，“加",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "我那个楼，”雷欧说，“有一间。不贵，大的。”他掏出手机，“加",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    companionPortraitKey: "suming-shame",
    companionSpeaker: "苏明",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "雷欧",
    mood: "restless",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
  {
    id: "d1_chapter_end",
    title: "导航把他们领进那条弯弯曲曲的旧巷。石家小楼还在更里头，灯是黄",
    purpose: "Draft adaptation beat.",
    visualPlaceholder: "导航把他们领进那条弯弯曲曲的旧巷。石家小楼还在更里头，灯是黄",
    backgroundKey: "rental-room",
    artKey: "bg-rental-room",
    portraitKey: "suming-shame",
    bgmKey: "night-ambient",
    sfxKey: "ui-click",
    speaker: "旁白",
    mood: "lonely",
    noncanonical: true,
    source: "supa-luv-v2-2026-07",
  },
] as const satisfies readonly PrototypeSceneCard[];
