import type { PrototypeSceneCard } from "@supaluv/shared";

export const prototypeScenes = [
  {
    id: "act1_office_shame_test",
    title: "Office Shame Test",
    purpose: "Establish the office test bench and Su Ming's awkward mood.",
    visualPlaceholder: "Office desk, monitor glow, untouched coffee.",
    backgroundKey: "office-night",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [{ label: "继续测试", to: "act1_lunch_forum_hint" }],
  },
  {
    id: "act1_lunch_forum_hint",
    title: "Lunch Forum Hint",
    purpose: "Let the prototype pivot from office stress to the companion-device market.",
    visualPlaceholder: "Food court table, phone screen, gray forum UI.",
    backgroundKey: "food-court",
    speaker: "旁白",
    mood: "restless",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [
      { label: "看物业照片", to: "act1_property_pickup" },
      { label: "跳过论坛直接回家", to: "act1_rental_room_search" },
    ],
  },
  {
    id: "act1_property_pickup",
    title: "Property Pickup",
    purpose: "Show breakup logistics and the last bag at the property desk.",
    visualPlaceholder: "Apartment lobby, white bag, erased access badge.",
    backgroundKey: "lobby-white",
    speaker: "旁白",
    mood: "sterile",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    autoNext: "act1_rental_room_search",
  },
  {
    id: "act1_rental_room_search",
    title: "Rental Room Search",
    purpose: "Move the prototype into a cramped private room and product curiosity.",
    visualPlaceholder: "Small rental room, dim lamp, phone in hand.",
    backgroundKey: "rental-room",
    speaker: "苏明",
    mood: "lonely",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [{ label: "点开产品页", to: "act1_product_page" }],
  },
  {
    id: "act1_product_page",
    title: "Product Page",
    purpose: "Reveal the clean sales page and the seductive promise.",
    visualPlaceholder: "Minimal product UI, price tag, clean white panel.",
    backgroundKey: "product-page",
    speaker: "旁白",
    mood: "tempted",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [
      { label: "立即支付", to: "act1_payment" },
      { label: "返回出租屋再想想", to: "act1_rental_room_search", kind: "return" },
    ],
  },
  {
    id: "act1_payment",
    title: "Payment",
    purpose: "End the tiny prototype on an irreversible-looking payment beat.",
    visualPlaceholder: "Phone payment confirmation, dark screen reflection.",
    backgroundKey: "payment-confirm",
    speaker: "旁白",
    mood: "committed",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
  },
] as const satisfies readonly PrototypeSceneCard[];
