import type { PrototypeSceneCard } from "@supaluv/shared";

export const prototypeScenes = [
  {
    id: "act1_office_shame_test",
    title: "Office Shame Test",
    purpose: "Plant the shame callback line and force the first mianzi/ai_score choice.",
    visualPlaceholder: "Office desk, monitor glow, frozen chat draft.",
    backgroundKey: "office-night",
    speaker: "苏明",
    mood: "shame",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [
      { label: "立刻删掉，假装什么都没发生", to: "act1_lunch_forum_hint" },
      { label: "先截图备份，万一以后用得上", to: "act1_coworker_peek" },
    ],
  },
  {
    id: "act1_coworker_peek",
    title: "Coworker Peek",
    purpose: "Escalate public-shame comedy before merging back to lunch.",
    visualPlaceholder: "Cubicle edge, coworker silhouette, screen reflection.",
    backgroundKey: "office-night",
    speaker: "苏明",
    mood: "panic",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [
      { label: "用身体挡住屏幕，随便胡扯", to: "act1_lunch_forum_hint" },
      { label: "诚实说：在测羞耻文案……算了还是胡扯", to: "act1_lunch_forum_hint" },
    ],
  },
  {
    id: "act1_lunch_forum_hint",
    title: "Lunch Forum Hint",
    purpose: "Pivot from office stress to companion-device market satire.",
    visualPlaceholder: "Food court table, phone screen, anonymous forum UI.",
    backgroundKey: "food-court",
    speaker: "旁白",
    mood: "restless",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [
      { label: "看物业发来的分手照片", to: "act1_property_pickup" },
      { label: "跳过现实，直接回家研究", to: "act1_rental_room_search" },
    ],
  },
  {
    id: "act1_property_pickup",
    title: "Property Pickup",
    purpose: "Sterile breakup logistics as deadpan comedy beat.",
    visualPlaceholder: "Apartment lobby, white bag, erased access badge.",
    backgroundKey: "lobby-white",
    speaker: "旁白",
    mood: "sterile",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    autoNext: "act1_rental_room_search",
  },
  {
    id: "act1_rental_room_search",
    title: "Rental Room Search",
    purpose: "Private room loneliness before product temptation.",
    visualPlaceholder: "Small rental room, dim lamp, half-typed search.",
    backgroundKey: "rental-room",
    speaker: "苏明",
    mood: "lonely",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [
      { label: "点开产品页", to: "act1_product_page" },
      { label: "先刷十分钟搞笑视频冷静", to: "act1_product_page" },
    ],
  },
  {
    id: "act1_product_page",
    title: "Product Page",
    purpose: "Sell 'won't judge you' as clean product copy for black comedy.",
    visualPlaceholder: "Minimal product UI, price tag, sterile feature list.",
    backgroundKey: "product-page",
    speaker: "旁白",
    mood: "tempted",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [
      { label: "立即支付，别给自己后悔的时间", to: "act1_demo_echo" },
      { label: "打开演示对话先试水", to: "act1_demo_echo" },
      { label: "返回出租屋再想想", to: "act1_rental_room_search", kind: "return" },
    ],
  },
  {
    id: "act1_demo_echo",
    title: "Demo Echo",
    purpose: "Pay off the office shame callback for the comedy punchline.",
    visualPlaceholder: "Chat demo overlay repeating the office draft line.",
    backgroundKey: "product-page",
    speaker: "演示对话",
    mood: "uncanny",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
    choices: [
      { label: "付款。这一次，别再假装自己很正常", to: "act1_payment" },
      { label: "关掉页面。明天再当正常人", to: "act1_payment" },
    ],
  },
  {
    id: "act1_payment",
    title: "Payment",
    purpose: "End on commitment comedy shaped by mianzi/ai_score meters.",
    visualPlaceholder: "Phone payment confirmation, dark screen reflection.",
    backgroundKey: "payment-confirm",
    speaker: "旁白",
    mood: "committed",
    noncanonical: true,
    source: "experimental-chapter-01-pipeline-dummy",
  },
] as const satisfies readonly PrototypeSceneCard[];
